name: Build Android APK

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        cache-dependency-path: 'qianduan/package-lock.json'
        
    - name: Setup Java
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '17'
        
    - name: Setup Android SDK
      uses: android-actions/setup-android@v3
      
    - name: Install frontend dependencies
      working-directory: ./qianduan
      run: npm ci
      
    - name: Build frontend
      working-directory: ./qianduan
      run: npm run build
      
    - name: Add Android platform
      working-directory: ./qianduan
      run: npx cap add android
      
    - name: Sync Capacitor
      working-directory: ./qianduan
      run: npx cap sync android
      
    - name: Build Android APK
      working-directory: ./qianduan/android
      run: ./gradlew assembleDebug
      
    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: android-apk
        path: qianduan/android/app/build/outputs/apk/debug/app-debug.apk
